import dotenv from 'dotenv';
dotenv.config();

export const {
  DATADOG_KEY,
  ACCESS_TOKEN_SECRET,
  EMAIL_VERIFICATION_TOKEN_EXPIRATION,
  ENVIRONMENT,
  HOST,
  S3_BUCKET_NAME,
  DEFAULT_EXPORT_FILE_EXPIRY_TIME,
  ICON_MAX_SIZE,
  MEDIACONVERTER_ENDPOINT,
  AWS_ROLE_ARN,
  DISTRIBUTED_URL
} = process.env;
